### PR TITLE
Issue #20 - single quote highlighting

### LINKED ISSUE #20: Apostrophe not parsed correctly
example:
```stylus
p= 'i should be parsed as string delimiter'
p i shouldn't be parsed as the beginning of a string 
```

i am seeing the second line being parsed incorrectly

### PR DESCRIPTION
**Pull request by tjefferson08**
Check out the commit messages! Closes #20.

### CODE REVIEW

**Comment by brianc** [comment]
Woo awesome!

**Comment by brianc** [comment]
@tjefferson08 do you want contributor access?

**Comment by tjefferson08** [comment]
Sure, contributor access would be great.

**Comment by brianc** [comment]
Rad - adding you now!

**Pull request merged**
